spring:
  application:
    name: bench
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  cache:
    type: caffeine
    cache-names: 
      - puntosDeVenta
    caffeine:
      spec: maximumSize=500,expireAfterWrite=10m
 
  jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
          ddl-auto: create
      show-sql: false
      
logging:
  level:
    org.springframework.cache: DEBUG
    com.example.demo.service: TRACE

